steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['generate']
  env: ['PROJECT_ROOT=github.com/g33kzone/go_webhooks']
- name: 'gcr.io/cloud-builders/go'
  args: ['test', './...']
  env: ['PROJECT_ROOT=github.com/g33kzone/go_webhooks']
- name: 'gcr.io/cloud-builders/go'
  args: ['install', '-a', '-ldflags', "'-s'", '-installsuffix', 'cgo', 'github.com/g33kzone/go_webhooks']
  env: [
    'PROJECT_ROOT=github.com/g33kzone/go_webhooks',
    'CGO_ENABLED=0',
    'GOOS=linux'
  ]  